#!/bin/bash                              

for number in $(seq 1 5)                  # For each number generated by the 'seq' command (1 to 5), store it in the variable 'number'.
do                                        # Start of the for loop.
    echo "Number: $number"                # Print the current value stored in the variable 'number'.
done                                      # End of the for loop.


# ====================================================================

#Run this command
#        ↓
#seq 1 5
#        ↓
#Produces

#1
#2
#3
#4
#5

#        ↓
# Use those values here

# ====================================================================

# Summary of the for loop:

# 1. C-style for loop
# for (( i=1; i<=5; i++ ))

# Use when: You want complete control over the start, condition, and increment.

# =======================================================================

# 2. Array for loop
# for fruit in "${fruits[@]}"

# Use when: You want to loop through every item in an array.

# =======================================================================

# 3. Command output for loop
# for number in $(seq 1 5)

# Use when: You want to loop through the output of a command (such as seq, ls, cat, etc.).

# ======================================================================

# You'll see $() all the time in Bash because it's the standard way to perform command substitution. It lets you run a command and use whatever it prints as part of another command.

# For example:

# today=$(date)

# Here, Bash runs date and stores its output in the variable today.

# This is one of the most common and useful pieces of Bash syntax you'll learn.